import Link from 'next/link';
import { Building2, GraduationCap, LineChart } from 'lucide-react';
import Nav from './components/Nav';

export default function Home(){
return <>
<Nav />
<main>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Credit education. Financial clarity. Real strategy.</div><h1>Reset your credit. Rebuild your confidence.</h1><p>The Financial Reset helps individuals and entrepreneurs understand their credit, create practical financial goals, and take informed steps toward stronger personal and business finances.</p><div className="hero-actions"><Link className="button primary" href="/portal">Start Your Reset</Link><a className="button secondary" href="#services">Explore Services</a></div></div><div className="hero-card"><div className="small">Your Financial Reset Roadmap</div><div className="score">3 Steps</div><h3>Understand. Plan. Progress.</h3><p className="small">A guided education-first experience designed to help you understand what is affecting your financial profile and what to do next.</p><div className="metrics"><div className="metric"><strong>1:1</strong><span>Guidance</span></div><div className="metric"><strong>Clear</strong><span>Action plans</span></div><div className="metric"><strong>Built</strong><span>For you</span></div></div></div></div></section>
<section className="section" id="services"><div className="container"><div className="section-head"><div className="eyebrow">What we help with</div><h2>Financial wellness built around your next chapter.</h2><p>Education and guidance for people who want to make smarter credit decisions, prepare for major goals, or build stronger business foundations.</p></div><div className="cards"><div className="card"><div className="icon"><GraduationCap size={22}/></div><h3>Personal Credit Education</h3><p>Understand credit reports, scoring factors, utilization, payment history, and how to create a personalized improvement plan.</p></div><div className="card"><div className="icon"><Building2 size={22}/></div><h3>Business Credit Guidance</h3><p>Learn how business credit works, what lenders review, and how to structure your business for stronger funding readiness.</p></div><div className="card"><div className="icon"><LineChart size={22}/></div><h3>Financial Wellness Coaching</h3><p>Create realistic habits, savings goals, debt strategies, and accountability systems that fit your lifestyle.</p></div></div></div></section>
<section className="section alt" id="process"><div className="container"><div className="section-head"><div className="eyebrow">The reset process</div><h2>A clear path forward.</h2></div><div className="steps"><div className="step"><span>01</span><h3>Complete intake</h3><p>Tell us your goals, challenges, and current situation.</p></div><div className="step"><span>02</span><h3>Choose a plan</h3><p>Select the education or coaching experience that fits your needs.</p></div><div className="step"><span>03</span><h3>Get your roadmap</h3><p>Receive clear priorities, next steps, and supporting resources.</p></div><div className="step"><span>04</span><h3>Track progress</h3><p>Use your portal to stay organized and follow your plan.</p></div></div></div></section>
<section className="section"><div className="container"><div className="cta"><div><h2>Ready for your financial reset?</h2><p>Start with a short intake so we can understand your goals and guide you toward the best next step.</p></div><Link className="button" style={{background:'#d6b66a',color:'#0c1b2a'}} href="/portal">Begin Intake</Link></div></div></section>
</main><footer className="footer"><div className="container footer-grid"><div>© 2026 The Financial Reset</div><div>Operated by Black Wealth Management LLC · Education only · Results vary</div></div></footer></>}
